/**
 * Generates `src/styles/tokens.css` from the sampled sources in
 * `src/config/palette.js`.
 *
 * The stylesheet is generated rather than hand-written so the hex values cannot
 * be edited away from the pixels that justify them. The palette gate
 * regenerates and diffs, so an edit to the emitted file fails the build.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { derive, GROUNDS, TOKENS, SOURCES } from '../src/config/palette.js';

const HERE = dirname(fileURLToPath(import.meta.url));
export const OUT = resolve(HERE, '../src/styles/tokens.css');

const pad = (s, n) => String(s).padEnd(n);
const wrap = (text, width, indent) => {
  const out = [];
  let line = '';
  for (const word of text.split(' ')) {
    if ((line + ' ' + word).trim().length > width) {
      out.push(indent + line.trim());
      line = word;
    } else line += ' ' + word;
  }
  if (line.trim()) out.push(indent + line.trim());
  return out;
};

export function render() {
  const rows = derive();
  const w = Math.max(...rows.map((r) => r.name.length));

  const head = [
    '/* Generated by scripts/palette.js. Do not edit: the palette gate',
    '   regenerates this file from src/config/palette.js and fails the build on',
    '   any drift.',
    '',
    '   PROVENANCE. Every colour below is traceable to a pixel in a file the',
    '   client supplied. Sampling method: per-element dominant colour,',
    '   cross-checked against the per-channel median. Not k-means: the artwork is',
    '   a two-element lockup, not a distribution to cluster, and clustering would',
    '   have invented intermediate colours no pixel holds.',
    '',
    '   The mark is white-only, so the ground is dark. That follows the artwork',
    '   as supplied; recolouring a client\'s mark is not ours to do.',
    '',
    '   Sources:',
    ...Object.entries(SOURCES).flatMap(([name, s]) => [
      `     ${name}  ${s.hex}  oklch(${s.L} ${s.C} ${s.H})  <- ${s.from}`,
      ...wrap(s.method, 68, '       '),
    ]),
    '',
    '   Hue and chroma are inherited from the source. Where a floor could not be',
    '   met, lightness ONLY was moved; those rows are marked relit. Ratios are',
    '   measured from the emitted hex, not the ideal coordinate, because the',
    '   shipped value is an 8-bit quantisation and that shifts the ratio.',
    '',
    '   token          coordinate                     hex      ' +
      GROUNDS.map((g) => pad(`on ${g}`, 12)).join('') +
      'floor   relit',
    ...rows.map(
      (r) =>
        '   ' +
        pad(r.name, w + 2) +
        pad(`oklch(${r.L.toFixed(4)} ${SOURCES[r.source].C} ${SOURCES[r.source].H})`, 31) +
        pad(r.hex, 9) +
        GROUNDS.map((g) => pad(`${r.ratios[g].toFixed(2)}:1`, 12)).join('') +
        pad(r.target === null ? 'n/a' : `${r.target}:1`, 8) +
        (r.relit ? 'yes' : 'no, as sampled')
    ),
    '*/',
    '',
  ];

  const body = [':root {', ...rows.map((r) => `  --${r.name}: ${r.hex};`), '}', ''];

  return head.concat(body).join('\n');
}

const runDirectly = process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url;

if (runDirectly) {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, render(), 'utf8');

  const rows = derive();
  process.stdout.write(`wrote ${OUT}\n`);
  process.stdout.write(`${TOKENS.length} tokens from ${Object.keys(SOURCES).length} sampled sources\n\n`);
  for (const r of rows) {
    const floors = r.target === null ? 'no floor' : `floor ${r.target}:1`;
    const ratios = GROUNDS.map((g) => `${g} ${r.ratios[g].toFixed(2)}:1`).join('  ');
    process.stdout.write(
      `  ${pad(r.name, 11)} ${r.hex}  ${ratios}  ${pad(floors, 13)}` +
        `drift ab ${r.driftAB.toFixed(5)} (H ${r.driftH.toFixed(2)} C ${r.driftC.toFixed(4)})  ` +
        `${r.inGamut ? '' : 'OUT OF GAMUT'}\n`
    );
  }
}
